routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('users.index');
});

Route::resources([
    'welcome' => 'QuestionsController',
    'superuser' => 'SurveyResultController'
]);

Route::get('/survey','QuestionsController@survey')->name('survey');

Route::get('/thanks', function(){
    return view('users.thanks');
})->name('thanks');

Route::get('/repair', 'QuestionsController@repair')->name('repair');
Route::post('/input-repair', 'QuestionsController@inputRepair')->name('input-repair');
Route::post('/answer', 'QuestionsController@answering')->name('answer');

Route::middleware('auth')->group(function(){
    Route::get('/index', 'UserController@index');
    Route::get('/table', 'UserController@table');
    Route::get('/user', 'UserController@user'); 
    Route::post('/user/create', 'UserController@store');
    Route::get('/editAdmin/{id}', 'UserController@edit');
    Route::get('/deleteAdmin/{id}', 'UserController@delete');
    Route::post('/updateAdmin/{id}', 'UserController@update');
    
    Route::post('/updatePeriod', 'SurveyResultController@updatePeriod');

    Route::get('/export', function(){ 
        return view('admin.export');
    });
    Route::post('/exportExcel', 'SurveyResultController@exportExcel');

    Route::get('/services' , 'AnswerOptionController@index');
    Route::get('/services/edit/{id}' , 'AnswerOptionController@edit');
    Route::get('/services/delete/{id}' , 'AnswerOptionController@destroy');
    Route::post('/services/update/{id}' , 'AnswerOptionController@update');
    Route::post('/services/add' , 'AnswerOptionController@store')->name('add-service');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function index() {
        // $data_option = Option::all();
        // return view("admin.index",['data_option' => $data_option]);   
    }


    public function table() {
        return view("admin.tabel");   
    }

    public function user() {
        $user = User::all();
        return view("admin.user", ['lihat' => $user]);
    }

    public function store(Request $request)
    {
        $User = new User;
        $User->name = $request->name;
        $User->email = $request->email;
        $User->password = $request->password;
        $User->save();
        return redirect('/user')->with('sukses', 'Data Berhasil di Masukan');
    }

    public function edit($id) 
    {
        $user = User::find($id);
        return view('/admin/edit', ['user' => $user]);
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user -> update($request->all());
        return redirect('/user')->with('sukses', 'Data Berhasil di Update');
    }

    public function delete($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect('/user')->with('sukses', 'Data Berhasil di Hapus');
    }
}

resources/views/users/header.blade.php
<header id="header">
    <div class="container">
      <div id="logo" class="pull-left">
        <a href="{{route('welcome.index')}}">
            <img src="{{ asset('img') }}/logo.png" alt="" title="" />
        </a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="{{route('welcome.index')}}">Lembaga Pemasyarakatan Kelas 1 Madiun</a></li>
        </ul>
      </nav>
      <nav class="pull-right d-none d-lg-inline">
        <ul class="nav-menu pull-right">
            <a href="#"><i class="fa fa-twitter"></i> | Lapas Klas I Madiun</a> 
            <a href="#"><i class="fa fa-facebook"></i> | Lapas Madiun</a>
        </ul>
      </nav>
    </div>
</header>

resources/views/users/index.blade.php
@extends('users.main')
@section('content')
  <section class="hero">
    <div class="container text-center">
      <div class="row">
        <div class="col-md-12">
          <a class="hero-brand" href="index.html" title="Home"><img style="width:100px; height:100px;" alt="Bell Logo" src="{{ asset('img') }}/logo.png"></a>
        </div>
      </div>

      <div class="col-md-12">
        <h1>
            Selamat Datang
          </h1>

        <p class="tagline">
          Lembaga Pemasyarakatan Kelas 1 Madiun
        </p>
        <a class="btn btn-full" href="/survey">Mulai Sekarang</a>
      </div>
    </div>

  </section>
@endsection()

resources/views/users/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>LAPAS KELAS 1 MADIUN</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">
  <meta name="csrf-token" content="{!! Session::token() !!}">

  <!-- Facebook Opengraph integration: https://developers.facebook.com/docs/sharing/opengraph -->
  <meta property="og:title" content="">
  <meta property="og:image" content="">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:description" content="">

  <!-- Twitter Cards integration: https://dev.twitter.com/cards/  -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="">
  <meta name="twitter:title" content="">
  <meta name="twitter:description" content="">
  <meta name="twitter:image" content="">

  <!-- Favicon -->
  <link href="{{ asset('img') }}/favicon.ico" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,700|Roboto:400,900" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{{ asset('lib') }}/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{{ asset('lib') }}/font-awesome/css/font-awesome.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{{ asset('css') }}/style.css" rel="stylesheet">
  <link href="{{ asset('css') }}/icheck-bootstrap.css" rel="stylesheet">


</head>

<body id="main">
    @yield('content')
  <footer class="site-footer">
    <div class="bottom">
      <div class="container">
        <div class="row">

          <div class="col-lg-6 col-xs-12 text-lg-left text-center">
            <p class="copyright-text">
              © LAPAS KELAS 1 MADIUN
            </p>
        </div>
      </div>
    </div>
  </footer>
  <a class="scrolltop" href="#"><span class="fa fa-angle-up"></span></a>


  <!-- Required JavaScript Libraries -->
  <script src="{{ asset('lib') }}/jquery/jquery.min.js"></script>
  <script src="{{ asset('lib') }}/jquery/jquery-migrate.min.js"></script>
  <script src="{{ asset('lib') }}/superfish/hoverIntent.js"></script>
  <script src="{{ asset('lib') }}/superfish/superfish.min.js"></script>
  <script src="{{ asset('lib') }}/tether/js/tether.min.js"></script>
  <script src="{{ asset('lib') }}/stellar/stellar.min.js"></script>
  <script src="{{ asset('lib') }}/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('lib') }}/counterup/counterup.min.js"></script>
  <script src="{{ asset('lib') }}/waypoints/waypoints.min.js"></script>
  <script src="{{ asset('lib') }}/easing/easing.js"></script>
  <script src="{{ asset('lib') }}/stickyjs/sticky.js"></script>
  <script src="{{ asset('lib') }}/parallax/parallax.js"></script>
  <script src="{{ asset('lib') }}/lockfixed/lockfixed.min.js"></script>

  <script src="{{ asset('js') }}/custom.js"></script>

  <script src="{{ asset('contactform') }}/contactform.js"></script>

  <script>
    function openForm(e) {
      var id_question = e.getAttribute("data-id_question");
      var id_answer = e.getAttribute("data-id_answer");
      console.log(id_answer);
      $.post("{{route('answer')}}",{
         _token: $('meta[name=csrf-token]').attr('content'),
          id_question: id_question,
          id_answer: id_answer
      }).fail(function(){
        alert("Error");
      });

      document.getElementById("myForm").style.display = "block";

      setTimeout(function(){
          window.location.href= "{{route('survey')}}";
      }, 5000);
    }
  </script>
</body>
</html>

resources/views/users/repair.blade.php
@extends('users.main')
@section('content')
  <!-- Header -->
  @include('users.header')
  <!-- #header -->

  <!-- About -->
   <section class="about bg-image" style="padding-bottom: 70px!important;">
        <div class="container">
            <div class="alert alert-info">
                <center><h4><b>{{$data['question']->question}}</b></h4></center>
            </div><!--/register-req-->
            
            <div class="shopper-informations">
                 <div class="row">
                       <div class="col-sm-6">
                          <div class="shopper-info" style="padding:80px;">
                            <form action="{{route('input-repair')}}" method="post">
                             {{ csrf_field() }}
                              @foreach($data['answer'] as $answer)
                              <div class="checkbox icheck-primary">
                                <input type="checkbox" id="{{$answer->id}}" name="id_answer[]" value="{{$answer->id}}"/>
                                <label style="font-size: 20px; font-weight: 600;" for="{{$answer->id}}">{{$answer->answer}}</label>
                                <input type="hidden" name="id_question" value="{{$data['question']->id}}">
                              </div>
                              @endforeach
                              <input type="submit" class="btn-submit-repair btn btn-full" value="Submit">
                            </form>        
                          </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="order-message">
                                <img src="img/tanya.png"  alt="" />
                            </div>  
                        </div>                
               </div>
            </div>
            
        </div>
    </section> <!--/#cart_items-->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script type="text/javascript">
    setTimeout(function(){
        window.location.href= "{{route('survey')}}";
    }, 10000);
  </script>

@endsection()

resources/views/users/survey.blade.php
@extends('users.main')
@section('content')
  <!-- Header -->
  @include('users.header')
  <!-- #header -->

  <!-- About -->
  <section class="about bg-image" id="about">
    <div class="container text-center">
      <h2>
          {{$data['question']->question}}
      </h2>

      <div class="row stats-row">
        @foreach($data['answer'] as $answer)
          @if($answer->answer != "Buruk" && $answer->answer != "Sangat Buruk")
            <div class="stats-col text-center col-md-4 col-sm-6">
                <form action="{{route('answer')}}" method="post">
                  {{ csrf_field() }}
                  <input class="hover-custom" type="image" src="{{ asset('img') }}/{{$answer->answer}}.png" 
                    alt="Submit" width="140" height="140">
                    <br>
                  <input type="hidden" name="id_question" value="{{$data['question']->id}}">
                  <input type="hidden" name="id_answer" value="{{$answer->id}}">
                </form>
                <h3>{{$answer->answer}}</h3>
            </div>
          @endif
        @endforeach
      </div>
      <style>
        body {font-family: Arial, Helvetica, sans-serif;}
        * {box-sizing: border-box;}

        /* The popup form - hidden by default */
        .form-popup {
          display: none;
          position: fixed;
          bottom: 200px;
          right: 250px;

          z-index: 9;
        }

        /* Add styles to the form container */
        .form-container {
          max-width: 1000px;
          padding: 80px 70px;
          background-color: #1f3c88;
          opacity: 0.8;
        }

        /* Set a style for the submit/login button */
        .form-container .btn {
          background-color: #4CAF50;
          color: white;
          padding: 20px 20px;
          border: none;
          cursor: pointer;
          width: 30%;
          margin-bottom:5px;
          opacity: 0.8;
        }

        /* Add a red background color to the cancel button */
        .form-container .cancel {
          background-color: red;
        }

        /* Add some hover effects to buttons */
        .form-container .btn:hover, .open-button:hover {
          opacity: 1;
        }

        .option-2{
          margin-right: 160px;
          margin-left: 160px;
        }
      </style>
      <div class="row stats-row option-2">
        @foreach($data['answer'] as $answer)
          @if($answer->answer == "Buruk" || $answer->answer == "Sangat Buruk")
        <div class="stats-col text-center col-md-6 col-sm-6">
            <input onclick="openForm(this)" class="hover-custom" type="image" name="emot" 
              data-id_question="{{$data['question']->id}}" data-id_answer="{{$answer->id}}"
              src="{{ asset('img') }}/{{$answer->answer}}.png" alt="Submit" width="140" height="140"
              readonly>
              <br>
            <h3>{{$answer->answer}}</h3>
        </div>
          @endif
        @endforeach
        <div class="form-popup" id="myForm">
          <form action="{{route('repair')}}" class="form-container">
            <h1 style="font-size: 15pt; color: white">Apakah Anda mau membantu kami melakukan penilaian selanjutnya?</h1><br><br>
            <button type="submit" class="btn" onclick>YA</button>
            <button type="button" class="btn cancel" onclick="window.location.href='{{route('thanks')}}'">TIDAK</button>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection()

resources/views/users/thanks.blade.php
@extends('users.main')
@section('content')
@include('users.header')
  <!-- #header -->

  <!-- About -->
  <!-- /About -->
   <section class="about bg-image">
        <div class="container">
            <!-- <div class="alert alert-info">
                <center><h4><b>Terimakasih Telah Memberikan Penilaian Pada Layanan Kami!</b></h4></center>
            </div> -->
            
           <br><br>
            <div class="shopper-informations">
                 <div class="row mb-5">
                        <div class="col-sm-2">
                        </div>
                        <div class="col-sm-4">
                            <div class="alert alert-info" style="margin-top: 9rem;">
                                <center><h4><b>Terimakasih Telah Memberikan Penilaian Pada Layanan Kami!</b></h4></center>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="order-message">
                                <img src="img/tanya.png"  alt="" />
                            </div>  
                        </div>
                        <div class="col-sm-2">
                        </div>
               </div>
            </div>
            <br>
        </div>
    </section> <!--/#cart_items-->

  <script src="contactform/contactform.js"></script>
  <script type="text/javascript">
    setTimeout(function(){
        window.location.href= "{{route('survey')}}";
    }, 2000);
  </script>
@endsection()